#@data/values
---
smbBrokerUsername: ""
smbBrokerPassword: ""

targetNamespace: cf-workloads
namespace: cf-smb
replicaCount: 1
smbbroker:
  fullname: smb-broker
  name: smb-broker

image:
  repository: cfpersi/smb-broker
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - "/v2"

service:
  type: ClusterIP
  port: 80
